<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RG-L200315-1397" failures="1" tests="1" name="test" time="3.315" errors="0" timestamp="2024-08-21T16:13:26 IST">
  <testcase classname="testcases.TC_003_LoginDDT" name="TestLogin_1" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: .\testdata\Login_data.xlsx (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: .\testdata\Login_data.xlsx (The system cannot find the path specified)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.io.FileNotFoundException: .\testdata\Login_data.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at utilities.excelutility.getRowCount(excelutility.java:34)
at utilities.Dataprovider.getData(Dataprovider.java:17)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TestLogin_1 -->
</testsuite> <!-- test -->
